### ISSUE TITLE
handle containers waiting status

### ISSUE THREAD

**Issue by helder-moreira** [NibiruChain/cosmopilot#205]
```
- image: ghcr.io/nibiruchain/node-utils:2.4.1
    imageID: ""
    lastState: {}
    name: node-utils
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "ghcr.io/nibiruchain/node-utils:2.4.1"
        reason: ImagePullBackOff
 ```
